"use strict";
const page = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OHCAYGO Merge Proof</title>
<style>body{max-width:960px;margin:48px auto;padding:0 24px;font:17px/1.6 system-ui;color:#18242b;background:#f7f8f5}h1{font-size:44px;line-height:1.1}section{padding:24px 0;border-top:1px solid #ccd4d5}button,a,select{font:inherit}button{padding:10px 18px;margin:6px 8px 6px 0;cursor:pointer}select{max-width:100%;padding:8px}a{color:#145c57}pre{white-space:pre-wrap;overflow-wrap:anywhere}#status{padding:16px;background:#e6ece8}li{margin:12px 0}[hidden]{display:none}</style>
<header><a href="/">OHCAYGO Merge Proof</a><h1>PROVE THE MERGE.</h1><p>Exact-state evidence for the change you’re about to merge.</p></header>
<p id="status" role="status">Connect GitHub to see your repositories and receipts.</p>
<section><a href="/proof/login">Connect / reconnect GitHub</a> · <a href="https://github.com/ohcaygo/merge-proof#readme">Use free local CLI / Action</a><p>We read repository evidence and publish receipt Checks. Select only the repositories you want covered. No AI model makes the proof decision.</p><a id="install" hidden>Install on selected repositories</a><p><label>GitHub account <select id="installation"><option>Select account</option></select></label></p><p><label>Repository <select id="repository"><option>Select repository</option></select></label></p><button id="logout">Disconnect this session</button><p>Uninstall or change repository access in GitHub App settings. Uninstall stops new proofs and denies hosted receipt access; accounting history is preserved for reconnect.</p></section>
<div id="workspace" hidden><section><h2>Hosted proofs</h2><p id="usage"></p><button id="refresh">Refresh account</button></section>
<section><h2>Optional historical scan</h2><p>One free scan: up to 5 merged PRs from the 30 most recently updated closed PRs. Squash/rebase history is unsupported; current rules cannot prove historical approvals. No live-proof allowance is consumed.</p><button id="scan">Start / retry same scan</button><button id="skip">Skip to first proof</button><button id="cancelScan">Cancel scan</button><button id="scanStatus">Refresh scan progress</button><pre id="scanResult"></pre></section>
<section id="firstProof"><h2>Prepare a receipt</h2><label>Open pull request <select id="pull"></select></label><button id="run">Prove selected PR</button><p>Completed VERIFIED and NOT_PROVEN receipts use one proof per new head. Failed collection and FAIL consume zero. Same-head refreshes consume zero additional proofs.</p><ul id="receipts"></ul></section>
<section><h2>Pro — $29/month per active developer</h2><p>50 proofs × paid active developers, pooled across this paying account. We count distinct human GitHub IDs opening covered PRs or pushing covered commits during the subscription month. Bots are excluded; human attribution requires GitHub evidence. Initial count uses the last 30 days of observed covered activity.</p><pre id="developers"></pre><p>Subscription starts at checkout. Included proofs reset at renewal without rollover. Purchased top-ups remain until consumed and are used after included proofs. No automatic top-up or overage charge. Quantity increases require your confirmation; no proration. Decreases apply at renewal.</p><button id="subscribe">Review and subscribe</button><button id="topup">Add 5 hosted proofs — $5</button><button id="quantity">Confirm active-developer quantity for renewal</button><button id="portal">Manage subscription</button></section></div>
<footer><p>Questions? <a href="mailto:support@ohcaygo.com">support@ohcaygo.com</a></p></footer><script src="/proof/app.js"></script></html>`;
const script = `"use strict";
const $=id=>document.getElementById(id);let account;
const scope=()=>({installation:Number($("installation").value),repository:Number($("repository").value)});
async function api(path,body){const r=await fetch('/proof/'+path,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
function status(s){$('status').textContent=s;}
function bind(id,fn){$(id).onclick=()=>Promise.resolve().then(fn).catch(e=>status(e.message==='ALLOWANCE_EXHAUSTED'?'Your allowance is used. Existing receipts and the free local CLI remain available. Upgrade or buy a top-up; no automatic charge.':e.message==='LOGIN_REQUIRED'?'Connect GitHub to continue.':e.message));}
function option(select,value,text){const o=document.createElement('option');o.value=value;o.textContent=text;select.append(o);}
async function load(){const q=new URLSearchParams(scope());account=await api('account?'+q);$('workspace').hidden=false;const u=account.usage;$('usage').textContent=u.plan+' — '+u.used+' used · '+u.remaining+' remaining · included '+u.includedBalance+' · top-ups '+u.topupBalance+'. '+(u.resetAt?'Reset: '+u.resetAt:u.resetExplanation);$('developers').textContent=u.activeDevelopers.length+' active developers · expected $'+(29*u.activeDevelopers.length)+'/month · '+(50*u.activeDevelopers.length)+' proofs/month\\n'+u.activeDevelopers.map(d=>d.login+': '+d.activity.map(a=>a.kind+' at '+new Date(a.at).toISOString()).join(', ')).join('\\n');$('pull').replaceChildren();for(const p of account.pulls)option($('pull'),p.number,'#'+p.number+' '+p.title);$('receipts').replaceChildren();for(const r of account.receipts){const li=document.createElement('li'),a=document.createElement('a');a.href='/proof/receipts/'+r.id;a.textContent='PR #'+r.pr+' · '+r.verdict+' · '+r.current+' · '+r.issuedAt;li.append(a);$('receipts').append(li);}status(new URLSearchParams(location.search).has('checkout')&&u.plan!=='PRO'?'Confirming subscription. Access changes only after verified payment; refresh to check.':'Account refreshed.');}
$('installation').onchange=async()=>{try{const d=await api('repositories?installation='+Number($('installation').value));$('repository').replaceChildren();option($('repository'),'','Select repository');for(const r of d.repositories)option($('repository'),r.id,r.name);}catch(e){status(e.message);}};
$('repository').onchange=()=>load().catch(e=>status(e.message));
bind('refresh',load);bind('run',async()=>{status('Collecting exact-state evidence…');const d=await api('run',{...scope(),pr:Number($('pull').value)});status(d.receipt.verdict+' — receipt saved.');await load();});
bind('scan',async()=>{await api('scan',scope());status('Scan started. Refresh scan progress to see results.');});bind('scanStatus',async()=>{$('scanResult').textContent=JSON.stringify(await api('scan?'+new URLSearchParams(scope())),null,2);});bind('cancelScan',async()=>{await api('scan/cancel',scope());status('Scan cancellation requested.');});bind('skip',()=>{$('firstProof').scrollIntoView();});
bind('subscribe',async()=>{const n=account.usage.activeDevelopers.length;if(!account.billingOwner){status('Only the paying account owner can manage billing.');return;}if(!n){status('No human covered activity observed yet. Open a covered PR or push a covered commit, then refresh.');return;}if(confirm('Subscribe for '+n+' active developers at $'+29*n+'/month, with '+50*n+' included proofs?'))location.href=(await api('checkout',{...scope(),kind:'pro',quantity:n})).url;});
bind('quantity',async()=>{const n=account.usage.activeDevelopers.length;if(confirm('Set the next monthly invoice to '+n+' developers at $'+29*n+'? No current-period proration.')){const d=await api('quantity',{...scope(),quantity:n});status(d.message+' Effective: '+d.effectiveAt);}});
bind('topup',async()=>{if(confirm('Purchase 5 additional hosted proofs for $5?'))location.href=(await api('checkout',{...scope(),kind:'topup'})).url;});bind('portal',async()=>{location.href=(await api('portal',scope())).url;});bind('logout',async()=>{await api('logout',{});location.href='/proof/';});
api('installations').then(d=>{for(const i of d.installations)option($('installation'),i.id,i.account);if(d.installUrl){$('install').href=d.installUrl;$('install').hidden=false;}status(d.installations.length?'Select an account and repository.':'Install the GitHub App on selected repositories, then reconnect.');}).catch(e=>status(e.message==='LOGIN_REQUIRED'?'Connect GitHub to begin.':e.message));`;
module.exports = { page, script };
