"use strict";
const page = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OHCAYGO Merge Proof</title>
<style>body{max-width:960px;margin:48px auto;padding:0 24px;font:17px/1.6 system-ui;color:#18242b;background:#f7f8f5}h1{font-size:44px;line-height:1.1}section{padding:24px 0;border-top:1px solid #ccd4d5}button,a,select{font:inherit}button{padding:10px 18px;margin:6px 8px 6px 0;cursor:pointer}select{max-width:100%;padding:8px}a{color:#145c57}pre{white-space:pre-wrap;overflow-wrap:anywhere}#status{padding:16px;background:#e6ece8}li{margin:12px 0}[hidden]{display:none!important}.primary{display:inline-block;background:#145c57;color:white;padding:12px 20px;border-radius:4px;text-decoration:none;font-weight:700}button:disabled{opacity:.5;cursor:default}a:focus-visible,button:focus-visible,select:focus-visible{outline:3px solid #3687bb;outline-offset:3px}@media(max-width:600px){body{margin:24px auto;padding:0 18px}h1{font-size:34px}button{max-width:100%}.primary{box-sizing:border-box;width:100%;text-align:center}}</style>
<header><a href="/">OHCAYGO Merge Proof</a><h1>PROVE THE MERGE.</h1><p>Before you merge, make sure the green lights actually belong to the code that's there now.</p></header>
<section id="welcome"><h2>TRY MERGE PROOF FREE</h2><p><strong>5 hosted proofs + 1 bounded historical scan. No card required.</strong></p><p>You'll need a GitHub account, a repository you can authorize, and an open PR for your first live proof.</p><p>Connect GitHub so we can show repositories you can access. Then install the App on the repositories you choose. We read repository evidence and publish receipt Checks.</p><p><a id="connect" class="primary" href="/proof/login">CONNECT GITHUB</a></p><p>Next: choose repository → choose open PR → get your Merge Proof receipt.</p><p>Prefer local? <a href="https://github.com/ohcaygo/merge-proof#readme">Free CLI + GitHub Action →</a></p></section>
<p id="status" role="status">Connect GitHub to begin. No payment is required for the free taste.</p>
<section id="connected" hidden><h2>Step 1 — Choose repository</h2><p id="installHelp">Choose an account and repository below, or install the App to authorize another repository.</p><a id="install" class="primary" hidden>INSTALL ON SELECTED REPOSITORIES</a><button id="reloadInstallations">Refresh connected repositories</button><p><label>GitHub account <select id="installation"><option value="">Select account</option></select></label></p><p><label>Repository <select id="repository" disabled><option value="">Select repository</option></select></label></p><button id="logout">Disconnect this session</button><p>Uninstall or change repository access in GitHub App settings. Uninstall stops new proofs and denies hosted receipt access; accounting history is preserved for reconnect.</p></section>
<div id="workspace" hidden><section><h2>Hosted proofs</h2><p id="usage"></p><button id="refresh">Refresh account</button></section>
<section id="firstProof"><h2>Step 2 — Choose open PR</h2><p id="noPulls" hidden>No open PRs found in this repository. Open a PR, then come back here and refresh open PRs. You can also run your free historical scan below.</p><label>Open pull request <select id="pull"></select></label><button id="refreshPulls">Refresh open PRs</button><h2>Step 3 — Get your Merge Proof receipt</h2><button id="run" disabled>GET MERGE PROOF RECEIPT</button><p>Completed VERIFIED and NOT_PROVEN receipts use one proof per new head. Failed collection and FAIL consume zero. Same-head refreshes consume zero additional proofs.</p><p>VERIFIED: the checked evidence claims were established for this exact state. NOT_PROVEN: some required evidence could not be established; this does not mean broken, buggy or unsafe code. STALE: the PR changed after the receipt and needs a new proof.</p><ul id="receipts"></ul></section>
<section><h2>Optional free historical scan</h2><p>See how Merge Proof evaluates evidence from recent merges in this repository.</p><p>One free scan: up to 5 merged PRs from the 30 most recently updated closed PRs. Squash/rebase history is unsupported; current rules cannot prove historical approvals. No live-proof allowance is consumed.</p><button id="scan">Start / retry same scan</button><button id="skip">Go to live proof</button><button id="cancelScan">Cancel scan</button><button id="scanStatus">Refresh scan progress</button><pre id="scanResult"></pre></section>
<section><h2>Pro — $29/month per active developer</h2><p>50 proofs × paid active developers, pooled across this paying account. We count distinct human GitHub IDs opening covered PRs or pushing covered commits during the subscription month. Bots are excluded; human attribution requires GitHub evidence. Initial count uses the last 30 days of observed covered activity.</p><pre id="developers"></pre><p>Subscription starts at checkout. Included proofs reset at renewal without rollover. Purchased top-ups remain until consumed and are used after included proofs. No automatic top-up or overage charge. Quantity increases require your confirmation; no proration. Decreases apply at renewal.</p><button id="subscribe">Review and subscribe</button><button id="topup">Add 5 hosted proofs — $5</button><button id="quantity">Confirm active-developer quantity for renewal</button><button id="portal">Manage subscription</button></section></div>
<footer><p>Questions? <a href="mailto:support@ohcaygo.com">support@ohcaygo.com</a></p></footer><script src="/proof/app.js"></script></html>`;
const script = `"use strict";
const $=id=>document.getElementById(id);let account;let selectionVersion=0;
const scope=()=>({installation:Number($("installation").value),repository:Number($("repository").value)});
async function api(path,body){const r=await fetch('/proof/'+path,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
function status(s){$('status').textContent=s;}
const source=new URLSearchParams(location.search).get('source');if(['x','other','direct'].includes(source))$('connect').href='/proof/login?source='+source;
function bind(id,fn){$(id).onclick=()=>Promise.resolve().then(fn).catch(e=>status(e.message==='ALLOWANCE_EXHAUSTED'?'Your allowance is used. Existing receipts and the free local CLI remain available. Upgrade or buy a top-up; no automatic charge.':e.message==='LOGIN_REQUIRED'?'Connect GitHub to continue.':e.message));}
function option(select,value,text){const o=document.createElement('option');o.value=value;o.textContent=text;select.append(o);}
async function load(){const version=++selectionVersion;const q=new URLSearchParams(scope());$('workspace').hidden=true;$('run').disabled=true;if(!scope().installation||!scope().repository)return;const next=await api('account?'+q);if(version!==selectionVersion)return;account=next;$('workspace').hidden=false;const u=account.usage;$('usage').textContent=u.plan+' — '+u.used+' used · '+u.remaining+' remaining · included '+u.includedBalance+' · top-ups '+u.topupBalance+'. '+(u.resetAt?'Reset: '+u.resetAt:u.resetExplanation);$('developers').textContent=u.activeDevelopers.length+' active developers · expected $'+(29*u.activeDevelopers.length)+'/month · '+(50*u.activeDevelopers.length)+' proofs/month\\n'+u.activeDevelopers.map(d=>d.login+': '+d.activity.map(a=>a.kind+' at '+new Date(a.at).toISOString()).join(', ')).join('\\n');$('pull').replaceChildren();for(const p of account.pulls)option($('pull'),p.number,'#'+p.number+' '+p.title);$('noPulls').hidden=account.pulls.length>0;$('pull').disabled=!account.pulls.length;$('run').disabled=!account.pulls.length;$('receipts').replaceChildren();for(const r of account.receipts){const li=document.createElement('li'),a=document.createElement('a');a.href='/proof/receipts/'+r.id;a.textContent='PR #'+r.pr+' · '+r.verdict+' · '+r.current+' · '+r.issuedAt;li.append(a);$('receipts').append(li);}status(new URLSearchParams(location.search).has('checkout')&&u.plan!=='PRO'?'Confirming subscription. Access changes only after verified payment; refresh to check.':account.pulls.length?'Choose an open PR, then get your receipt.':'No open PRs found. Open a PR and refresh, or try the historical scan.');}
$('installation').onchange=async()=>{const version=++selectionVersion;$('workspace').hidden=true;$('repository').disabled=true;$('repository').replaceChildren();option($('repository'),'','Select repository');if(!scope().installation)return;try{const d=await api('repositories?installation='+scope().installation);if(version!==selectionVersion)return;for(const r of d.repositories)option($('repository'),r.id,r.name);$('repository').disabled=!d.repositories.length;status(d.repositories.length?'Choose a repository.':'No authorized repositories found. Install the App on a repository you can authorize, then refresh connected repositories.');}catch(e){status(e.message);}};
$('repository').onchange=()=>load().catch(e=>status(e.message));
bind('refresh',load);bind('refreshPulls',load);bind('run',async()=>{if(!Number($('pull').value))return;$('run').disabled=true;status('Collecting evidence. Your receipt will open when ready…');try{const d=await api('run',{...scope(),pr:Number($('pull').value)});location.href=d.url;}finally{$('run').disabled=false;}});
bind('scan',async()=>{await api('scan',scope());status('Scan started. Refresh scan progress to see results.');});bind('scanStatus',async()=>{$('scanResult').textContent=JSON.stringify(await api('scan?'+new URLSearchParams(scope())),null,2);});bind('cancelScan',async()=>{await api('scan/cancel',scope());status('Scan cancellation requested.');});bind('skip',()=>{$('firstProof').scrollIntoView();});
bind('subscribe',async()=>{const n=account.usage.activeDevelopers.length;if(!account.billingOwner){status('Only the paying account owner can manage billing.');return;}if(!n){status('No human covered activity observed yet. Open a covered PR or push a covered commit, then refresh.');return;}if(confirm('Subscribe for '+n+' active developers at $'+29*n+'/month, with '+50*n+' included proofs?'))location.href=(await api('checkout',{...scope(),kind:'pro',quantity:n})).url;});
bind('quantity',async()=>{const n=account.usage.activeDevelopers.length;if(confirm('Set the next monthly invoice to '+n+' developers at $'+29*n+'? No current-period proration.')){const d=await api('quantity',{...scope(),quantity:n});status(d.message+' Effective: '+d.effectiveAt);}});
bind('topup',async()=>{if(confirm('Purchase 5 additional hosted proofs for $5?'))location.href=(await api('checkout',{...scope(),kind:'topup'})).url;});bind('portal',async()=>{location.href=(await api('portal',scope())).url;});bind('logout',async()=>{await api('logout',{});location.href='/proof/';});
async function installations(){++selectionVersion;$('workspace').hidden=true;$('repository').disabled=true;$('repository').replaceChildren();option($('repository'),'','Select repository');const d=await api('installations');$('welcome').hidden=true;$('connected').hidden=false;$('installation').replaceChildren();option($('installation'),'','Select account');for(const i of d.installations)option($('installation'),i.id,i.account);if(d.installUrl){$('install').href=d.installUrl;$('install').hidden=false;}$('installHelp').textContent=d.installations.length?'Choose an account and repository below, or install the App to authorize another repository.':'Install the GitHub App on a repository you can authorize. Return here after installation and refresh connected repositories.';status(d.installations.length?'Choose an account and repository.':'GitHub connected. Install the App on selected repositories to continue.');}
bind('reloadInstallations',installations);installations().catch(e=>status(e.message==='LOGIN_REQUIRED'?(new URLSearchParams(location.search).has('login')?'GitHub connection was canceled or unavailable. Use CONNECT GITHUB to try again.':'Connect GitHub to begin. No payment is required for the free taste.'):e.message));`;
module.exports = { page, script };
