"use strict";
const page = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Merge Proof · Prove the merge</title><style>body{font:18px/1.5 system-ui;background:#f1f4ef;color:#172a29;padding:24px}main{max-width:600px;margin:40px auto;background:white;border:1px solid #cad5cd;border-radius:16px;padding:32px}label{display:block;margin:18px 0}input{font:inherit;padding:8px;max-width:95%}button{font:inherit;background:#174f43;color:white;padding:12px 20px;border:0;border-radius:8px}small{display:block;margin-top:24px;color:#53655c}</style><main><p>MERGE PROOF</p><h1>Prove the merge.</h1><p>Get a receipt for what GitHub evidence establishes about an exact change. No AI review. No source tree sent to a model.</p><form id="proof"><label>Public GitHub repository<br><input name="repo" placeholder="owner/repository" required></label><label>Open pull request number<br><input name="pr" type="number" min="1" required></label><label><input name="publish" type="checkbox"> Make this public repository receipt shareable</label><button>Collect evidence</button><p id="status" role="status"></p></form><small>Anonymous GitHub access may not expose repository rules or workflow evidence. Missing evidence stays NOT_PROVEN. Private repositories require an authorized API client; browser GitHub sign-in is not implemented.</small></main><script src="/proof/app.js" defer></script></html>`;
const script = `function bind(){const form=document.querySelector('#proof');if(form)form.addEventListener('submit',async e=>{e.preventDefault();const b=form.querySelector('button'),status=document.querySelector('#status');b.disabled=true;status.textContent='Collecting the exact state and applicable evidence…';try{const data=new FormData(form);const response=await fetch('/proof/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({repo:data.get('repo'),pr:Number(data.get('pr')),publish:data.get('publish')==='on'})});const out=await response.json();if(!response.ok)throw Error(out.error);if(!data.get('publish')){status.textContent='Receipt created. Save its JSON now; this unshared receipt requires an authorized repository API client to retrieve later.';const blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='merge-proof-receipt.json';link.textContent='Save receipt JSON';status.append(' ',link);}else location.assign(out.url);}catch(e){status.textContent='Evidence unavailable or request denied. Retry after checking repository access.';}finally{b.disabled=false;}});const refresh=document.querySelector('#refresh-proof');if(refresh)refresh.addEventListener('click',async()=>{refresh.disabled=true;try{const response=await fetch(location.pathname+'/refresh?format=html',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!response.ok)throw Error();const doc=new DOMParser().parseFromString(await response.text(),'text/html');document.querySelector('main').replaceWith(doc.querySelector('main'));bind();}catch{refresh.textContent='Refresh unavailable. Historical receipt unchanged.';refresh.disabled=false;}});}bind();`;
const interactive = (document) =>
  document.replace(
    "</main>",
    '<button id="refresh-proof" type="button">Refresh current evidence</button></main><script src="/proof/app.js" defer></script>',
  );
module.exports = { page, script, interactive };
